table 000_tblLocations
	lineageTag: 486af6ca-195f-4402-97cd-6b4f33ec1261

	column Acronym
		dataType: string
		lineageTag: b2ebde89-f958-4119-b24a-c696e600015e
		summarizeBy: none
		sourceColumn: Acronym

		annotation SummarizationSetBy = Automatic

	column Full-Location
		dataType: string
		lineageTag: 31acf392-aab3-4958-ae99-fd64533341e5
		summarizeBy: none
		sourceColumn: Full-Location

		annotation SummarizationSetBy = Automatic

	partition 000_tblLocations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCnZU0lEKzi8tyVBwLC0uKUrMyUzUQTCVYnWilcJBasJTi0tSi/Jwq/ILDgcq80stV4AYF56Yk1qMrijM0xmoKCwzuSS/CM2IWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Acronym = _t, #"Full-Location" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Acronym", type text}, {"Full-Location", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

