table 000_tblHeadcount
	lineageTag: 8d5709c2-5678-4663-9b50-a962c3ba2d07

	column Organisation
		dataType: string
		lineageTag: 4a8b2058-521d-4847-abea-c70f574eaf9b
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 15d1463d-1389-422d-aaff-f22bf1863a96
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column 'FTE total'
		dataType: double
		lineageTag: 3ba209f5-7ef3-4aec-8e80-f205acf3243a
		summarizeBy: sum
		sourceColumn: FTE total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'FTE notkilleveryoneism'
		dataType: double
		lineageTag: c38d52af-60d4-4747-9584-d5277bbd0c7f
		summarizeBy: sum
		sourceColumn: FTE notkilleveryoneism

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: string
		lineageTag: fa6443b7-aab7-4b03-b856-547cbb37b954
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'Revenue total'
		dataType: string
		lineageTag: bc8b7f92-83af-4911-975b-1a2a9e4efd95
		summarizeBy: none
		sourceColumn: Revenue total

		annotation SummarizationSetBy = Automatic

	column 'Revenue notkilleveryoneism'
		dataType: string
		lineageTag: f3d63a3d-bbac-41e2-b798-1b304c49a578
		summarizeBy: none
		sourceColumn: Revenue notkilleveryoneism

		annotation SummarizationSetBy = Automatic

	partition 000_tblHeadcount = m
		mode: import
		queryGroup: 1-Extract
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1zEiH7vRUdsV5oiYUqm0kHBdVJHJjveYz1IDTWHWsApI/"),
				    Headcount_Table = Source{[name="Headcount",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Headcount_Table, [PromoteAllScalars=true]),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers1",{""}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([Date] <> null and [Date] <> "")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"FTE notkilleveryoneism", type number}, {"FTE total", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

