table 000_tblOrg
	lineageTag: 489adb6f-eb7f-4d47-9cce-1808ec99e5c8

	column Organisation
		dataType: string
		lineageTag: 6575ac16-7e65-4883-a4c5-ce9e0d57d455
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: d88073ea-9afd-460e-b977-94c92a915fea
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column Mission
		dataType: string
		lineageTag: 15d19ba0-4863-468d-a2cb-56579dcda1ea
		summarizeBy: none
		sourceColumn: Mission

		annotation SummarizationSetBy = Automatic

	column 'Activities AI'
		dataType: string
		lineageTag: c7e9fd0f-bb4e-443c-9c73-d356fe9cca0c
		summarizeBy: none
		sourceColumn: Activities AI

		annotation SummarizationSetBy = Automatic

	column Misc
		dataType: string
		lineageTag: ea62f274-3f4f-4c12-9153-d357e173d48d
		summarizeBy: none
		sourceColumn: Misc

		annotation SummarizationSetBy = Automatic

	column 'Parent org'
		dataType: string
		lineageTag: cc7a916e-3867-450a-a32e-8011a9de0453
		summarizeBy: none
		sourceColumn: Parent org

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 4dc27541-437e-4e36-a8aa-43c52dfe2438
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Key Contacts'
		dataType: string
		lineageTag: 2cdf78c5-a870-4930-9b3a-ee2d978aca00
		summarizeBy: none
		sourceColumn: Key Contacts

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 56a7e333-9291-4306-80dd-617188d25047
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Organisation-Shortened.1'
		dataType: string
		lineageTag: ebacd467-97e1-42e8-a855-156afe9f6264
		summarizeBy: none
		sourceColumn: Organisation-Shortened.1

		annotation SummarizationSetBy = Automatic

	column 'Organisation-Shortened.2'
		dataType: string
		lineageTag: 69f57346-aa20-405c-97d4-08b31aaa2807
		summarizeBy: none
		sourceColumn: Organisation-Shortened.2

		annotation SummarizationSetBy = Automatic

	column Organisation-Shortened
		dataType: string
		lineageTag: 9757e405-3a53-4a6d-8be2-c7f9c1436368
		summarizeBy: none
		sourceColumn: Organisation-Shortened

		annotation SummarizationSetBy = Automatic

	partition 000_tblOrg = m
		mode: import
		queryGroup: 1-Extract
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1zEiH7vRUdsV5oiYUqm0kHBdVJHJjveYz1IDTWHWsApI/"),
				    Organisations_Table = Source{[name="Organisation",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Organisations_Table, [PromoteAllScalars=true]),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers", [PromoteAllScalars=true]),
				    #"Removed Columns1" = Table.RemoveColumns(#"Promoted Headers1",{""}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Removed Columns1",1),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Bottom Rows", "Organisation", "Organisation-Shortened"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Duplicated Column", "Organisation-Shortened", Splitter.SplitTextByEachDelimiter({"("}, QuoteStyle.Csv, true), {"Organisation-Shortened.1", "Organisation-Shortened.2"}),
				    #"Replaced Value23" = Table.ReplaceValue(#"Split Column by Delimiter",")","",Replacer.ReplaceText,{"Organisation-Shortened.2"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value23", "Organisation-Shortened", each if [#"Organisation-Shortened.2"] = null then [#"Organisation-Shortened.1"] else [#"Organisation-Shortened.2"]),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Conditional Column","University","Uni",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value","Australian Capital Territory","ACT",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value10","Western Australia","WA",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","Queensland","QLD",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value15","New South Wales","NSW",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","Victoria","VIC",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","South Australia","SA",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value13","Australians","Aussies",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Effective Altruism","EA",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Artificial Intelligence","AI",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","Technology","Tech",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value9","Governance","Gov",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Government","Govt",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Australian","Aus",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Federal","Fed",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Australia","Aus",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value5","Mathematic","Math",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","Group","Grp",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","International","Intl",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","Development","Dev",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19"," and"," &",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","Intelligence","Intell.",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","Commonwealth Scientific & Industrial Research Organisation (CSIRO)","CSIRO",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value22","Institute","Institute",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value25" = Table.ReplaceValue(#"Replaced Value24","Conference","Conf",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","Fundamentals","Fundies",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","Institute","Inst.",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","Automated","Auto.",Replacer.ReplaceText,{"Organisation-Shortened"}),
				    #"Replaced Value29" = Table.ReplaceValue(#"Replaced Value28","Existential","Exist.",Replacer.ReplaceText,{"Organisation-Shortened"})
				in
				    #"Replaced Value29"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

