table 005_tblOrg-SplitContacts
	lineageTag: e8280f09-4dfc-42d8-b54d-575d574ec819

	column Organisation
		dataType: string
		lineageTag: d1fbf9f8-6b0f-47df-8d6e-f17ddaf1f59b
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: cfb40a8f-d20e-4f56-a9a2-961f5dcbf51f
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 754720f9-8ee6-47c8-87cf-149872c08282
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Link
		dataType: string
		lineageTag: 960fd371-c4cd-441e-bf42-c9da2b3c3592
		summarizeBy: none
		sourceColumn: Link

		annotation SummarizationSetBy = Automatic

	column IsMain
		dataType: string
		lineageTag: f2b05872-cb06-4a5e-9d45-f9b64d417eed
		summarizeBy: none
		sourceColumn: IsMain

		annotation SummarizationSetBy = Automatic

	partition 005_tblOrg-SplitContacts = m
		mode: import
		queryGroup: 2-Transform
		source =
				let
				    Source = #"000_tblOrg",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Organisation", "Key Contacts"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Other Columns", each ([Key Contacts] <> "")),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows1", "KeyContactsWithMarker", each "(main)" & [Key Contacts]),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Added Custom", {{"KeyContactsWithMarker", Splitter.SplitTextByDelimiter("#(lf)", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "KeyContactsWithMarker"),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Split Column by Delimiter", "KeyContactsWithMarker", Splitter.SplitTextByEachDelimiter({","}, QuoteStyle.Csv, false), {"Name", "TitleAndLink"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Split Column by Delimiter1","(","(https://",Replacer.ReplaceText,{"TitleAndLink"}),
				    #"Split Column by Delimiter2" = Table.SplitColumn(#"Replaced Value", "TitleAndLink", Splitter.SplitTextByEachDelimiter({"("}, QuoteStyle.Csv, false), {"Title", "Link"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Split Column by Delimiter2",")","",Replacer.ReplaceText,{"Link"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value1", "IsMain", each if Text.StartsWith([Name], "(main)") then "Main" else "Secondary"),
				    #"Replaced Value2" = Table.ReplaceValue(#"Added Conditional Column","(main)","",Replacer.ReplaceText,{"Name"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value2",{"Key Contacts"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

