table 005_tblOrg-SplitParents
	lineageTag: d96f7834-2f02-4171-8577-00660fd7c095

	column Organisation
		dataType: string
		lineageTag: 87567ae4-f352-4938-aba9-0f4c150f9abc
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column Organisation-Shortened
		dataType: string
		lineageTag: 102f53f7-44aa-421e-b967-ab39e9dec67a
		summarizeBy: none
		sourceColumn: Organisation-Shortened

		annotation SummarizationSetBy = Automatic

	column 'Parent org'
		dataType: string
		lineageTag: 10908696-2305-4649-94cf-742ca6a0be27
		summarizeBy: none
		sourceColumn: Parent org

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: 26fe2c3b-3f26-474a-9039-6fd61d351278
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column 'Parent org-base'
		dataType: string
		lineageTag: 7cd37354-9419-478c-8d98-58d86eaec9b6
		summarizeBy: none
		sourceColumn: Parent org-base

		annotation SummarizationSetBy = Automatic

	column 'Parent org-acronym'
		dataType: string
		lineageTag: f0b72015-a2db-460d-a834-2f457810e03d
		summarizeBy: none
		sourceColumn: Parent org-acronym

		annotation SummarizationSetBy = Automatic

	column 'Parent org-shortened'
		dataType: string
		lineageTag: 91da608c-ea9d-4aa0-af0d-3b7d40c3a407
		summarizeBy: none
		sourceColumn: Parent org-shortened

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: fb96bb0d-dce2-4167-b150-8937556f9a92
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column LocationParent
		dataType: string
		lineageTag: 0aef7443-7bc8-4402-8c8d-d358caaff5a5
		summarizeBy: none
		sourceColumn: LocationParent

		annotation SummarizationSetBy = Automatic

	partition 005_tblOrg-SplitParents = m
		mode: import
		queryGroup: 2-Transform\Influences
		source =
				let
				    Source = #"000_tblOrg",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Organisation", "Organisation-Shortened", "Parent org", "URL", "Location"}),
				    #"Split Parent org by ," = Table.ExpandListColumn(Table.TransformColumns(#"Removed Other Columns", {{"Parent org", Splitter.SplitTextByDelimiter(", ", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "Parent org"),
				    #"Duplicated Parent org" = Table.DuplicateColumn(#"Split Parent org by ,", "Parent org", "Parent org-shortened"),
				    #"Split Parent org-shortened by (" = Table.SplitColumn(#"Duplicated Parent org", "Parent org-shortened", Splitter.SplitTextByEachDelimiter({"("}, QuoteStyle.Csv, false), {"Parent org-base", "Parent org-acronym"}),
				    #"Replaced ) in Parent org-acronym" = Table.ReplaceValue(#"Split Parent org-shortened by (",")","",Replacer.ReplaceText,{"Parent org-acronym"}),
				    #"Added Parent org-shortened" = Table.AddColumn(#"Replaced ) in Parent org-acronym", "Parent org-shortened", each if [#"Parent org-acronym"] = null then [#"Parent org-base"] else [#"Parent org-acronym"]),
				    #"Merged with Org" = Table.NestedJoin(#"Added Parent org-shortened", {"Parent org"}, #"000_tblOrg", {"Organisation"}, "000_tblOrg", JoinKind.LeftOuter),
				    #"Expanded 000_tblOrg" = Table.ExpandTableColumn(#"Merged with Org", "000_tblOrg", {"Location"}, {"LocationParent"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded 000_tblOrg"," aka Industry House","",Replacer.ReplaceText,{"Location", "LocationParent"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

