table 010_Hierarchy
	lineageTag: 1b0ff087-9ecd-4948-962c-1ed2335ff8c0

	column Level1
		dataType: string
		lineageTag: 619737c0-bfd0-4fc6-b754-419f4513df63
		summarizeBy: none
		sourceColumn: Level1

		annotation SummarizationSetBy = Automatic

	column Level2
		dataType: string
		lineageTag: 73451c26-5922-46b7-b0a5-68329ff6e90f
		summarizeBy: none
		sourceColumn: Level2

		annotation SummarizationSetBy = Automatic

	column Level3
		dataType: string
		lineageTag: abe92382-9702-4d9a-9bd1-589b9c9c0f45
		summarizeBy: none
		sourceColumn: Level3

		annotation SummarizationSetBy = Automatic

	column Level4
		dataType: string
		lineageTag: c09e9214-9152-46bc-9e5c-c2fbe7bfd7c3
		summarizeBy: none
		sourceColumn: Level4

		annotation SummarizationSetBy = Automatic

	column Level5
		dataType: string
		lineageTag: e38e9f8b-d613-4e6d-8280-6d16f9ddab75
		summarizeBy: none
		sourceColumn: Level5

		annotation SummarizationSetBy = Automatic

	column Level6
		dataType: string
		lineageTag: 6c511817-efbf-4f2c-86b4-7ce6d6bce23a
		summarizeBy: none
		sourceColumn: Level6

		annotation SummarizationSetBy = Automatic

	column Lvl2
		dataType: string
		lineageTag: 88750d50-9546-4ae4-b8eb-e9f25d949697
		summarizeBy: none
		sourceColumn: Lvl2

		annotation SummarizationSetBy = Automatic

	column Lvl3
		dataType: string
		lineageTag: 13f8a9cc-c157-485a-8959-1fa189ec3477
		summarizeBy: none
		sourceColumn: Lvl3

		annotation SummarizationSetBy = Automatic

	column Lvl4
		dataType: string
		lineageTag: 0f66654c-83e0-47d9-9055-044de1df316c
		summarizeBy: none
		sourceColumn: Lvl4

		annotation SummarizationSetBy = Automatic

	column Lvl5
		dataType: string
		lineageTag: ee912051-f300-4d45-ab5a-d8c0b41ea1a8
		summarizeBy: none
		sourceColumn: Lvl5

		annotation SummarizationSetBy = Automatic

	column Level7
		dataType: string
		lineageTag: 1e15b43f-1341-44aa-82a3-4ce33273e1a6
		summarizeBy: none
		sourceColumn: Level7

		annotation SummarizationSetBy = Automatic

	column Level2URL
		dataType: string
		lineageTag: 40e98e37-f2e1-435b-8f5e-37a9a10f56ea
		summarizeBy: none
		sourceColumn: Level2URL

		annotation SummarizationSetBy = Automatic

	column Level3URL
		dataType: string
		lineageTag: 01a53520-b77f-471f-9312-1886193c7935
		summarizeBy: none
		sourceColumn: Level3URL

		annotation SummarizationSetBy = Automatic

	column URL-Main
		dataType: string
		lineageTag: ce76d8a2-4fb1-4a34-97d7-1e090a79a178
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL-Main

		annotation SummarizationSetBy = Automatic

	column URL-Secondary
		dataType: string
		lineageTag: dfba53ee-1014-45b9-8a1f-ae426ef98c7f
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL-Secondary

		annotation SummarizationSetBy = Automatic

	column LowestLevelOrg
		dataType: string
		lineageTag: 3fc495bb-8cfa-4dbc-b25a-3f95f4d3b1e3
		summarizeBy: none
		sourceColumn: LowestLevelOrg

		annotation SummarizationSetBy = Automatic

	column Level4URL
		dataType: string
		lineageTag: be0c3863-b156-4161-a881-431cea08f4c1
		summarizeBy: none
		sourceColumn: Level4URL

		annotation SummarizationSetBy = Automatic

	column Level5URL
		dataType: string
		lineageTag: 24aade85-0be7-4b96-a643-26cb9e6f97d4
		summarizeBy: none
		sourceColumn: Level5URL

		annotation SummarizationSetBy = Automatic

	column Level6URL
		dataType: string
		lineageTag: 4149b56d-160a-44c2-ba63-1112ff9040a2
		summarizeBy: none
		sourceColumn: Level6URL

		annotation SummarizationSetBy = Automatic

	column Level7URL
		dataType: string
		lineageTag: 1e4b8f84-3a6d-4959-9a16-c850a0056ec3
		summarizeBy: none
		sourceColumn: Level7URL

		annotation SummarizationSetBy = Automatic

	partition 010_Hierarchy = m
		mode: import
		queryGroup: 2-Transform
		source =
				let
				    Source = "World",
				    #"Converted to Table" = #table(1, {{Source}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Level1"}}),
				    #"Merged Queries Level2" = Table.NestedJoin(#"Renamed Columns", {"Level1"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded Level2" = Table.ExpandTableColumn(#"Merged Queries Level2", "005_tblOrg-SplitParents", {"Organisation", "Organisation-Shortened", "URL"}, {"Level2", "Lvl2", "Level2URL"}),
				    #"Merged Queries Level3" = Table.NestedJoin(#"Expanded Level2", {"Level2"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded Level3" = Table.ExpandTableColumn(#"Merged Queries Level3", "005_tblOrg-SplitParents", {"Organisation", "Organisation-Shortened", "URL"}, {"Level3", "Lvl3", "Level3URL"}),
				    #"Merged Queries Level4" = Table.NestedJoin(#"Expanded Level3", {"Level3"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded Level4" = Table.ExpandTableColumn(#"Merged Queries Level4", "005_tblOrg-SplitParents", {"Organisation", "Organisation-Shortened", "URL"}, {"Level4", "Lvl4", "Level4URL"
				}),
				    #"Merged Queries Level5" = Table.NestedJoin(#"Expanded Level4", {"Level4"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded Level5" = Table.ExpandTableColumn(#"Merged Queries Level5", "005_tblOrg-SplitParents", {"Organisation", "Organisation-Shortened", "URL"}, {"Level5", "Lvl5", "Level5URL"}),
				    #"Merged Queries Level6" = Table.NestedJoin(#"Expanded Level5", {"Level5"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded Level6" = Table.ExpandTableColumn(#"Merged Queries Level6", "005_tblOrg-SplitParents", {"Organisation", "URL"}, {"Level6", "Level6URL"}),
				    #"Merged Queries Level7" = Table.NestedJoin(#"Expanded Level6", {"Level6"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded Level7" = Table.ExpandTableColumn(#"Merged Queries Level7", "005_tblOrg-SplitParents", {"Organisation", "URL"}, {"Level7", "Level7URL"}),
				    #"Added URL-Combined" = Table.AddColumn(#"Expanded Level7", "URL-Combined", each if [Level7] <> null then [Level7URL] else if [Level6] <> null then [Level6URL] else if [Level5] <> null then [Level5URL] else if [Level4] <> null then [Level4URL] else if [Level3] <> null then [Level3URL] else if [Level2] <> null then [Level2URL] else null),
				    #"Sorted Rows" = Table.Sort(#"Added URL-Combined",{{"Level3", Order.Ascending}}),
				    #"Added LowestLevelOrg" = Table.AddColumn(#"Sorted Rows", "LowestLevelOrg", each if [Level7] <> null then [Level7] else if [Level6] <> null then [Level6] else if [Level5] <> null then [Level5] else if [Level4] <> null then [Level4] else if [Level3] <> null then [Level3] else if [Level2] <> null then [Level2] else [Level1]),
				    #"Replaced Value URL-Combined" = Table.ReplaceValue(#"Added LowestLevelOrg","(","https://",Replacer.ReplaceText,{"URL-Combined"}),
				    #"Replaced Value1 URL-Combined" = Table.ReplaceValue(#"Replaced Value URL-Combined",")","",Replacer.ReplaceText,{"URL-Combined"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Replaced Value1 URL-Combined", "URL-Combined", Splitter.SplitTextByEachDelimiter({"#(lf)"}, QuoteStyle.Csv, false), {"URL-Main", "URL-Secondary"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Split Column by Delimiter",null,"No child orgs",Replacer.ReplaceValue,{"Level2", "Lvl2", "Level3", "Lvl3", "Level4", "Lvl4", "Level5", "Lvl5", "Level6", "Level7"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

