table 010_Organisations
	lineageTag: 489adb6f-eb7f-4d47-9cce-1808ec99e5c8

	column Organisation
		dataType: string
		lineageTag: 6575ac16-7e65-4883-a4c5-ce9e0d57d455
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: d88073ea-9afd-460e-b977-94c92a915fea
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column 'Doc heading'
		dataType: string
		lineageTag: 971f2848-b5d4-4543-84ff-7bbac8529791
		summarizeBy: none
		sourceColumn: Doc heading

		annotation SummarizationSetBy = Automatic

	column Mission
		dataType: string
		lineageTag: 15d19ba0-4863-468d-a2cb-56579dcda1ea
		summarizeBy: none
		sourceColumn: Mission

		annotation SummarizationSetBy = Automatic

	column 'Activities general'
		dataType: string
		lineageTag: 9b76ef29-3d25-42d4-8c23-f7a41411d42f
		summarizeBy: none
		sourceColumn: Activities general

		annotation SummarizationSetBy = Automatic

	column 'Activities AI'
		dataType: string
		lineageTag: c7e9fd0f-bb4e-443c-9c73-d356fe9cca0c
		summarizeBy: none
		sourceColumn: Activities AI

		annotation SummarizationSetBy = Automatic

	column Misc
		dataType: string
		lineageTag: ea62f274-3f4f-4c12-9153-d357e173d48d
		summarizeBy: none
		sourceColumn: Misc

		annotation SummarizationSetBy = Automatic

	column 'Parent org'
		dataType: string
		lineageTag: cc7a916e-3867-450a-a32e-8011a9de0453
		summarizeBy: none
		sourceColumn: Parent org

		annotation SummarizationSetBy = Automatic

	column Locations
		dataType: string
		lineageTag: d98b0506-9786-4428-86aa-8ff98d0ecca5
		summarizeBy: none
		sourceColumn: Locations

		annotation SummarizationSetBy = Automatic

	column Headcount
		dataType: string
		lineageTag: 19c7a5a5-a928-4dae-bcfa-ffb4fd2e75e9
		summarizeBy: none
		sourceColumn: Headcount

		annotation SummarizationSetBy = Automatic

	column 'Headcount source'
		dataType: string
		lineageTag: 424d08cb-3d95-429d-a8e0-9ea92c2867ac
		summarizeBy: none
		sourceColumn: Headcount source

		annotation SummarizationSetBy = Automatic

	column Structure
		dataType: string
		lineageTag: a7a109d2-1e94-45f7-98b1-6504788fed23
		summarizeBy: none
		sourceColumn: Structure

		annotation SummarizationSetBy = Automatic

	column Address-Main
		dataType: string
		lineageTag: ee97c0b9-6491-4098-ba0d-022bd4e6ed72
		summarizeBy: none
		sourceColumn: Address-Main

		annotation SummarizationSetBy = Automatic

	partition 010_Organisations = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1zEiH7vRUdsV5oiYUqm0kHBdVJHJjveYz1IDTWHWsApI/"),
				    Organisations_Table = Source{[name="Organisations",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Organisations_Table, [PromoteAllScalars=true]),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers1",{"TODO: try adding more serious / colourcoding to charts.#(lf)Also split ""Activities AI"" into individual rows for another chart?"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

