table 010_tblOrg
	lineageTag: 489adb6f-eb7f-4d47-9cce-1808ec99e5c8

	column Organisation
		dataType: string
		lineageTag: 6575ac16-7e65-4883-a4c5-ce9e0d57d455
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: d88073ea-9afd-460e-b977-94c92a915fea
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column Mission
		dataType: string
		lineageTag: 15d19ba0-4863-468d-a2cb-56579dcda1ea
		summarizeBy: none
		sourceColumn: Mission

		annotation SummarizationSetBy = Automatic

	column 'Activities AI'
		dataType: string
		lineageTag: c7e9fd0f-bb4e-443c-9c73-d356fe9cca0c
		summarizeBy: none
		sourceColumn: Activities AI

		annotation SummarizationSetBy = Automatic

	column Misc
		dataType: string
		lineageTag: ea62f274-3f4f-4c12-9153-d357e173d48d
		summarizeBy: none
		sourceColumn: Misc

		annotation SummarizationSetBy = Automatic

	column 'Parent org'
		dataType: string
		lineageTag: cc7a916e-3867-450a-a32e-8011a9de0453
		summarizeBy: none
		sourceColumn: Parent org

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 4dc27541-437e-4e36-a8aa-43c52dfe2438
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Key Contacts'
		dataType: string
		lineageTag: 2cdf78c5-a870-4930-9b3a-ee2d978aca00
		summarizeBy: none
		sourceColumn: Key Contacts

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 56a7e333-9291-4306-80dd-617188d25047
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	partition 010_tblOrg = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1zEiH7vRUdsV5oiYUqm0kHBdVJHJjveYz1IDTWHWsApI/"),
				    Organisations_Table = Source{[name="Organisation",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Organisations_Table, [PromoteAllScalars=true]),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers", [PromoteAllScalars=true]),
				    #"Removed Columns1" = Table.RemoveColumns(#"Promoted Headers1",{""})
				in
				    #"Removed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

