table 010_tblOrg-events
	lineageTag: 32d25435-011d-4f2d-b13a-f73159591caa

	column Organisation
		dataType: string
		lineageTag: a24b7394-a77f-457a-b63d-3ce0f59a37af
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 53456777-228b-42c4-9e8e-ca3cea1a8801
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 11be9495-2622-47a5-b8d6-dcf9d98611db
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Event
		dataType: string
		lineageTag: d54ae7ea-883a-410e-aba3-bed84d21e229
		summarizeBy: none
		sourceColumn: Event

		annotation SummarizationSetBy = Automatic

	column Event-Type
		dataType: string
		lineageTag: 9cfd88b8-68e1-4b4e-b3a7-613c41f66953
		summarizeBy: none
		sourceColumn: Event-Type

		annotation SummarizationSetBy = Automatic

	column Index-Asc-ByOrgDate
		dataType: int64
		formatString: 0
		lineageTag: c44e4553-ce2f-45cc-bbbb-7044eeb5d1a6
		summarizeBy: sum
		sourceColumn: Index-Asc-ByOrgDate

		annotation SummarizationSetBy = Automatic

	column Index-Asc-ByDate
		dataType: int64
		formatString: 0
		lineageTag: ebc7f5f8-359c-47e1-89e8-80e15193f98c
		summarizeBy: sum
		sourceColumn: Index-Asc-ByDate

		annotation SummarizationSetBy = Automatic

	column Organisation-Shortened
		dataType: string
		lineageTag: dc36a542-cf8d-4386-9ce3-d1532435d418
		summarizeBy: none
		sourceColumn: Organisation-Shortened

		annotation SummarizationSetBy = Automatic

	column Date-NextEntry
		dataType: dateTime
		formatString: Long Date
		lineageTag: 21aa8ed4-3611-4190-bce5-73af953289af
		summarizeBy: none
		sourceColumn: Date-NextEntry

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DaysSincePreviousEntry
		dataType: int64
		formatString: 0
		lineageTag: 3a9f2234-2e0b-4d56-bbd5-9e3de1405132
		summarizeBy: sum
		sourceColumn: DaysSincePreviousEntry

		annotation SummarizationSetBy = Automatic

	column Index-Asc-ByDate-WithJumps
		dataType: double
		formatString: 0
		lineageTag: 1c0e6f69-f4d6-4765-a3f7-0628fd9b5cdb
		summarizeBy: sum
		sourceColumn: Index-Asc-ByDate-WithJumps

		annotation SummarizationSetBy = Automatic

	partition 010_tblOrg-events = m
		mode: import
		queryGroup: 2-Transform
		source =
				let
				    Source = #"000_tblOrg",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Organisation", "Organisation-Shortened", "Status"}),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Other Columns", {{"Status", Splitter.SplitTextByDelimiter("#(lf)", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "Status"),
				    #"Filtered Rows" = Table.SelectRows(#"Split Column by Delimiter", each ([Status] <> "" and [Status] <> "Active!" and [Status] <> "Formerly in CSIRO" and [Status] <> "Inactive" and [Status] <> "Not Yet Active")),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Filtered Rows", "Status", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Date", "Event"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Split Column by Delimiter1",":","",Replacer.ReplaceText,{"Date"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Date", type date}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type"),
				    #"Sorted Rows" = Table.Sort(#"Removed Errors",{{"Date", Order.Descending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
				    #"Sorted Rows1" = Table.Sort(#"Added Index",{{"Date", Order.Ascending}, {"Organisation", Order.Ascending}}),
				    #"Added Index1" = Table.AddIndexColumn(#"Sorted Rows1", "Index-Asc-ByOrgDate", 1, 1, Int64.Type),
				    #"Sorted Rows2" = Table.Sort(#"Added Index1",{{"Date", Order.Ascending}}),
				    #"Added Index2" = Table.AddIndexColumn(#"Sorted Rows2", "Index-Asc-ByDate", 1, 1, Int64.Type),
				    #"Replaced Value13" = Table.ReplaceValue(#"Added Index2","Founded","founded",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value13","Active","âš¡ Active",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","launch","ðŸš€ launch",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Merge","ðŸ¤ Merge",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","inactive","ðŸ’¤ inactive",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value6","Inactive","ðŸ’¤ inactive",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value18","founded","ðŸ‘¶ founded",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","ended","ðŸª¦ ended",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value2","created","ðŸ‘¶ created",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","started","ðŸ‘¶ started",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","moved","ðŸ¤moved",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","application","ðŸ“‹ application",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","incorporated","ðŸ‘¶ incorporated",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","announced","ðŸ“¢ announced",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value12","concept","ðŸ’¡ concept",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","milestone","ðŸŽ¯ milestone",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","active","âš¡ active",Replacer.ReplaceValue,{"Event"}),
				    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","published","ðŸ“„ published",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value17","consultation","ðŸ‘¥ consultation",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","start","âš¡ start",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","Start","âš¡ start",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","occurred","ðŸ“… occurred",Replacer.ReplaceText,{"Event"}),
				    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","event","ðŸ“… event",Replacer.ReplaceText,{"Event"}),
				    #"Added Event-Type" = Table.AddColumn(#"Replaced Value23", "Event-Type", each if Text.Contains([Event], "ðŸ‘¶") then "- ðŸ‘¶ founded" else if Text.Contains([Event], "ðŸª¦") then "-ðŸª¦ended" else if Text.Contains([Event], "ðŸ¤") then "- ðŸ¤ merged" else if Text.Contains([Event], "ðŸ’¤") then "- ðŸ’¤ inactive" else if Text.Contains([Event], "ðŸ“‹") then "- ðŸ“‹ application" else if Text.Contains([Event], "âš¡") then "- âš¡ active" else if Text.Contains([Event], "ðŸ“¢") then "- ðŸ“¢ announced" else if Text.Contains([Event], "ðŸ’¡") then "-ðŸ’¡ concept" else if Text.Contains([Event], "ðŸ“… ") then "- ðŸ“…  event" else if Text.Contains([Event], "ðŸš€") then "- ðŸš€ launch" else if Text.Contains([Event], "ðŸ‘¥") then "- ðŸ‘¥ consultation" else if Text.Contains([Event], "ðŸ“„") then "- ðŸ“„ published" else "- Misc"),
				    #"Merged Queries" = Table.NestedJoin(#"Added Event-Type", {"Index-Asc-ByDate"}, #"005_tblOrg-events-ForMerge", {"Index-Asc-ByDate-ForMerge"}, "005_tblOrg-events-ForMerge", JoinKind.LeftOuter),
				    #"Expanded 005_tblOrg-events-ForMerge" = Table.ExpandTableColumn(#"Merged Queries", "005_tblOrg-events-ForMerge", {"Date"}, {"Date-NextEntry"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded 005_tblOrg-events-ForMerge", "DaysSincePreviousEntry", each [#"Date-NextEntry"]-[Date]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"DaysSincePreviousEntry", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type1", "Index-Asc-ByDate-WithJumps", each if [DaysSincePreviousEntry] > 61 then [#"Index-Asc-ByDate"] else (Number.RandomBetween(1,10)*[#"Index-Asc-ByDate"])),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Index-Asc-ByDate-WithJumps", type number}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

