table 010_Hierarchy
	lineageTag: 1b0ff087-9ecd-4948-962c-1ed2335ff8c0

	column Level1
		dataType: string
		lineageTag: 619737c0-bfd0-4fc6-b754-419f4513df63
		summarizeBy: none
		sourceColumn: Level1

		annotation SummarizationSetBy = Automatic

	column Level2
		dataType: string
		lineageTag: 73451c26-5922-46b7-b0a5-68329ff6e90f
		summarizeBy: none
		sourceColumn: Level2

		annotation SummarizationSetBy = Automatic

	column Level3
		dataType: string
		lineageTag: abe92382-9702-4d9a-9bd1-589b9c9c0f45
		summarizeBy: none
		sourceColumn: Level3

		annotation SummarizationSetBy = Automatic

	column Level4
		dataType: string
		lineageTag: c09e9214-9152-46bc-9e5c-c2fbe7bfd7c3
		summarizeBy: none
		sourceColumn: Level4

		annotation SummarizationSetBy = Automatic

	column Level5
		dataType: string
		lineageTag: e38e9f8b-d613-4e6d-8280-6d16f9ddab75
		summarizeBy: none
		sourceColumn: Level5

		annotation SummarizationSetBy = Automatic

	column Level6
		dataType: string
		lineageTag: 6c511817-efbf-4f2c-86b4-7ce6d6bce23a
		summarizeBy: none
		sourceColumn: Level6

		annotation SummarizationSetBy = Automatic

	column Lvl2
		dataType: string
		lineageTag: 88750d50-9546-4ae4-b8eb-e9f25d949697
		summarizeBy: none
		sourceColumn: Lvl2

		annotation SummarizationSetBy = Automatic

	column Lvl3
		dataType: string
		lineageTag: 13f8a9cc-c157-485a-8959-1fa189ec3477
		summarizeBy: none
		sourceColumn: Lvl3

		annotation SummarizationSetBy = Automatic

	column Lvl4
		dataType: string
		lineageTag: 0f66654c-83e0-47d9-9055-044de1df316c
		summarizeBy: none
		sourceColumn: Lvl4

		annotation SummarizationSetBy = Automatic

	column Lvl5
		dataType: string
		lineageTag: ee912051-f300-4d45-ab5a-d8c0b41ea1a8
		summarizeBy: none
		sourceColumn: Lvl5

		annotation SummarizationSetBy = Automatic

	column Level7
		dataType: string
		lineageTag: 1e15b43f-1341-44aa-82a3-4ce33273e1a6
		summarizeBy: none
		sourceColumn: Level7

		annotation SummarizationSetBy = Automatic

	column Level2URL
		dataType: string
		lineageTag: 40e98e37-f2e1-435b-8f5e-37a9a10f56ea
		summarizeBy: none
		sourceColumn: Level2URL

		annotation SummarizationSetBy = Automatic

	column Level3URL
		dataType: string
		lineageTag: 01a53520-b77f-471f-9312-1886193c7935
		summarizeBy: none
		sourceColumn: Level3URL

		annotation SummarizationSetBy = Automatic

	column URL-Main
		dataType: string
		lineageTag: ce76d8a2-4fb1-4a34-97d7-1e090a79a178
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL-Main

		annotation SummarizationSetBy = Automatic

	column URL-Secondary
		dataType: string
		lineageTag: dfba53ee-1014-45b9-8a1f-ae426ef98c7f
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL-Secondary

		annotation SummarizationSetBy = Automatic

	partition 010_Hierarchy = m
		mode: import
		queryGroup: 2-Transform
		source =
				let
				    Source = "World",
				    #"Converted to Table" = #table(1, {{Source}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Level1"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Level1"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    Expandedtest = Table.ExpandTableColumn(#"Merged Queries", "005_tblOrg-SplitParents", {"Organisation", "Organisation-Shortened", "URL"}, {"Level2", "Lvl2", "Level2URL"}),
				    #"Merged Queries1" = Table.NestedJoin(Expandedtest, {"Level2"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded 000_tblOrg1" = Table.ExpandTableColumn(#"Merged Queries1", "005_tblOrg-SplitParents", {"Organisation", "Organisation-Shortened", "URL"}, {"Level3", "Lvl3", "Level3URL"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded 000_tblOrg1", {"Level3"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded 000_tblOrg2" = Table.ExpandTableColumn(#"Merged Queries2", "005_tblOrg-SplitParents", {"Organisation", "Organisation-Shortened"}, {"Level4", "Lvl4"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded 000_tblOrg2", {"Level4"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded 000_tblOrg3" = Table.ExpandTableColumn(#"Merged Queries3", "005_tblOrg-SplitParents", {"Organisation", "Organisation-Shortened"}, {"Level5", "Lvl5"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Expanded 000_tblOrg3", {"Level5"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded 000_tblOrg4" = Table.ExpandTableColumn(#"Merged Queries4", "005_tblOrg-SplitParents", {"Organisation"}, {"Level6"}),
				    #"Merged Queries5" = Table.NestedJoin(#"Expanded 000_tblOrg4", {"Level6"}, #"005_tblOrg-SplitParents", {"Parent org"}, "005_tblOrg-SplitParents", JoinKind.LeftOuter),
				    #"Expanded 000_tblOrg5" = Table.ExpandTableColumn(#"Merged Queries5", "005_tblOrg-SplitParents", {"Organisation"}, {"Level7"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Expanded 000_tblOrg5", "URL-Combined", each if [Level3URL] <> null then [Level3URL] else [Level2URL]),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Conditional Column","(","https://",Replacer.ReplaceText,{"URL-Combined"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",")","",Replacer.ReplaceText,{"URL-Combined"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Replaced Value1", "URL-Combined", Splitter.SplitTextByEachDelimiter({"#(lf)"}, QuoteStyle.Csv, false), {"URL-Main", "URL-Secondary"})
				in
				    #"Split Column by Delimiter"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

