table 020_ParentsHierarchy
	lineageTag: ca55b85c-a44e-472d-bc96-11d909e54d7d

	column Organisation
		dataType: string
		lineageTag: 54fcab4b-7047-45de-973b-a4ace5b0603b
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column 'Parent org'
		dataType: string
		lineageTag: 804f3a8c-ee9d-4d80-92da-931383003ab2
		summarizeBy: none
		sourceColumn: Parent org

		annotation SummarizationSetBy = Automatic

	partition 020_ParentsHierarchy = m
		mode: import
		source =
				let
				    Source = #"010_Organisations",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Organisation", "Parent org"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

