table Org
	lineageTag: a95f0817-2701-4284-b228-3549caa6e99c

	measure _mParent = (COUNTA(Org[Parent org])/countrows(Org))
		formatString: 0%;-0%;0%
		lineageTag: c68ac8bb-63a3-41ed-8d4e-55da9361200d

	measure _mURL = (COUNTA(Org[URL-Main])/countrows(Org))
		formatString: 0%;-0%;0%
		lineageTag: 38c7f6c1-b8e2-487b-aa9f-84eaccdceeb8

	measure _mOrgNamesPivoted = ```
			
			VAR CurrentRowIndex = 
			    RANKX(
			        FILTER(
			            ALLSELECTED(Org),
			            Org[OrgFirstLetter] = MAX(Org[OrgFirstLetter])
			        ),
			        Org[Organisation-Shortened],
			        ,
			        ASC
			    )
			VAR RowNumber = 
			    RANKX(
			        ALLSELECTED(Org),
			        CONCATENATE(Org[OrgFirstLetter], FORMAT(CurrentRowIndex, "000")),
			        ,
			        ASC
			    )
			RETURN
			    IF(
			        RowNumber = MAX(
			            RANKX(
			                ALLSELECTED(Org),
			                CONCATENATE(Org[OrgFirstLetter], FORMAT(CurrentRowIndex, "000")),
			                ,
			                ASC
			            )
			        ),
			        MAX(Org[Organisation-Shortened]),
			        BLANK()
			    )
			```
		lineageTag: 1ab4eac1-2693-498a-ac60-ae91df3e6927

	measure _mOrgNamesPivoted2b = ```
			
			VAR RowNum = SELECTEDVALUE('RowNumbers'[Value])
			VAR SelectedLetter = SELECTEDVALUE('Letters'[Letter])  // Need a Letters table
			VAR FilteredOrgs = 
			    FILTER(
			        ALLSELECTED(Org),
			        Org[OrgFirstLetter] = SelectedLetter
			    )
			VAR SortedOrgs = 
			    ADDCOLUMNS(
			        FilteredOrgs,
			        "RowRank", 
			        RANKX(FilteredOrgs, Org[Organisation-Shortened], , ASC)
			    )
			VAR SelectedOrg = 
			    FILTER(SortedOrgs, [RowRank] = RowNum)
			RETURN
			    MAXX(SelectedOrg, Org[Organisation-Shortened])
			```
		lineageTag: ac578940-afa2-4d6b-914f-f38c5e495f7f

	measure _mOrgNamesPivoted2a = ```
			
			VAR CurrentRow = SELECTEDVALUE(RowNumbers[Value])
			VAR CurrentLetter = SELECTEDVALUE(Org[OrgFirstLetter])
			VAR OrgsInLetter = 
			    CALCULATETABLE(
			        VALUES(Org[Organisation-Shortened]),
			        Org[OrgFirstLetter] = CurrentLetter
			    )
			VAR SortedOrgs = 
			    ADDCOLUMNS(
			        OrgsInLetter,
			        "RowRank", 
			        RANKX(OrgsInLetter, Org[Organisation-Shortened], , ASC)
			    )
			VAR SelectedOrg = 
			    FILTER(SortedOrgs, [RowRank] = CurrentRow)
			RETURN
			    MAXX(SelectedOrg, Org[Organisation-Shortened])
			```
		lineageTag: 0da9b063-349b-412f-abbd-458798ccb299

	column Organisation
		dataType: string
		lineageTag: af2a3529-8de3-40fa-ad3c-269749e0fef0
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column Mission
		dataType: string
		lineageTag: 6f63f450-3264-43a9-9dcc-62e463a6e74b
		summarizeBy: none
		sourceColumn: Mission

		annotation SummarizationSetBy = Automatic

	column 'Activities AI'
		dataType: string
		lineageTag: 436b501d-5207-43cf-9953-75a5549227cd
		summarizeBy: none
		sourceColumn: Activities AI

		annotation SummarizationSetBy = Automatic

	column Misc
		dataType: string
		lineageTag: 09a5a5ba-722f-4d86-adc8-54d30949eea1
		summarizeBy: none
		sourceColumn: Misc

		annotation SummarizationSetBy = Automatic

	column 'Parent org'
		dataType: string
		lineageTag: bd6b55e7-67a3-41b8-abdb-f74c820ad18e
		summarizeBy: none
		sourceColumn: Parent org

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 552c088e-97e4-4b97-890f-293dbecc4480
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Key Contacts'
		dataType: string
		lineageTag: 0f54e3d0-ad52-4b95-855d-fe38f04b5113
		summarizeBy: none
		sourceColumn: Key Contacts

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 91640236-cc0d-40f0-9e24-e4090118de10
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Organisation-Shortened.1'
		dataType: string
		lineageTag: 0f982550-d827-47e0-9cfb-8c5c0fc85843
		summarizeBy: none
		sourceColumn: Organisation-Shortened.1

		annotation SummarizationSetBy = Automatic

	column 'Organisation-Shortened.2'
		dataType: string
		lineageTag: df576ff7-1067-4f51-851f-fdb8f5d10758
		summarizeBy: none
		sourceColumn: Organisation-Shortened.2

		annotation SummarizationSetBy = Automatic

	column Organisation-Shortened
		dataType: string
		lineageTag: 1bbbf6e0-c2cb-466f-9956-3db1021d49df
		summarizeBy: none
		sourceColumn: Organisation-Shortened

		annotation SummarizationSetBy = Automatic

	column URL-Main
		dataType: string
		lineageTag: 2d2bdd68-9be6-4def-a8c1-7698cb7ca260
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL-Main

		annotation SummarizationSetBy = Automatic

	column URL-Secondary
		dataType: string
		lineageTag: d9bdd3fc-36ca-4e41-89bf-9532e5cd4ca3
		summarizeBy: none
		sourceColumn: URL-Secondary

		annotation SummarizationSetBy = Automatic

	column _%Location = (COUNTA(Org[Location])/countrows(Org))/countrows(Org)
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: 29a62380-9b9d-47a3-af51-f3eb8f8a9a96
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column _%Mission = (COUNTA(Org[Mission])/countrows(Org))/countrows(Org)
		formatString: 0%;-0%;0%
		lineageTag: 40803b1b-92b8-4467-894d-f37e847aa253
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ActiveOrNot
		dataType: string
		lineageTag: fd1b0518-2300-471b-a4ea-d75c1342bc2b
		summarizeBy: none
		sourceColumn: ActiveOrNot

		annotation SummarizationSetBy = Automatic

	column OrgStructure
		dataType: string
		lineageTag: bbf1fc55-7c61-4a42-8cc3-7d5a0c9e5c12
		summarizeBy: none
		sourceColumn: OrgStructure

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: d12c3d20-b57c-407c-bdc8-2a17dfd53811
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column _%Activities = (COUNTA(Org[Activities AI])/countrows(Org))/countrows(Org)
		formatString: 0%;-0%;0%
		lineageTag: 3a7d2c48-247b-4273-927e-faf3ffde2872
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column AIFocus
		dataType: string
		lineageTag: 0589a35e-fcab-4fd5-aad1-6bd775e1fd14
		summarizeBy: none
		sourceColumn: AIFocus

		annotation SummarizationSetBy = Automatic

	column URL-Main_Domain
		dataType: string
		lineageTag: 90cf1a98-265a-4017-9053-a5399d7a6384
		summarizeBy: none
		sourceColumn: URL-Main_Domain

		annotation SummarizationSetBy = Automatic

	column URL-Main_Subpage
		dataType: string
		lineageTag: 6ec4db8b-0e13-42e6-860a-c7b27ba27b37
		summarizeBy: none
		sourceColumn: URL-Main_Subpage

		annotation SummarizationSetBy = Automatic

	column Logo
		dataType: string
		lineageTag: a791df13-d97e-48ce-9ee1-6c49a702ecfe
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Logo

		annotation SummarizationSetBy = Automatic

	column _LogoAsText = Org[Logo]
		lineageTag: 8e5e1703-da66-4faa-914c-15b224cd6113
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column OrgFirstLetter
		dataType: string
		lineageTag: a6fdee3e-6ab9-4cdf-98fc-9b803b352c05
		summarizeBy: none
		sourceColumn: OrgFirstLetter

		annotation SummarizationSetBy = Automatic

	column _OrgNameContainsAOrI =
			
			IF(
			    AND(
			        OR(CONTAINSSTRING(Org[Organisation-Shortened], "A"), CONTAINSSTRING(Org[Organisation-Shortened], "I")),
			        LEN(Org[Organisation-Shortened]) < 8
			    ),
			    "Valid",
			    IF(LEN(Org[Organisation-Shortened]) >= 8, "Too long", "Missing A or I")
			)
		lineageTag: 555b2b54-95d1-49df-a439-fcb92cd36d30
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Org = m
		mode: import
		queryGroup: 3-Load
		source =
				let
				    Source = #"010_tblOrg-Formatting",
				    #"Replaced blanks with nulls" = Table.ReplaceValue(Source,"",null,Replacer.ReplaceValue,{"Organisation", "URL-Main", "URL-Secondary", "Mission", "Activities AI", "Status", "Key Contacts", "Parent org", "Location", "Misc", "Organisation-Shortened.1", "Organisation-Shortened.2", "Organisation-Shortened"}),
				    #"Replaced mere linefeeds with nulls" = Table.ReplaceValue(#"Replaced blanks with nulls","#(lf)",null,Replacer.ReplaceValue,{"Organisation", "URL-Main", "URL-Secondary", "Mission", "Activities AI", "Status", "Key Contacts", "Parent org", "Location", "Misc", "Organisation-Shortened.1", "Organisation-Shortened.2", "Organisation-Shortened"})
				in
				    #"Replaced mere linefeeds with nulls"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

