table Org
	lineageTag: a95f0817-2701-4284-b228-3549caa6e99c

	measure _mParent = (COUNTA(Org[Parent org])/countrows(Org))
		formatString: 0%;-0%;0%
		lineageTag: c68ac8bb-63a3-41ed-8d4e-55da9361200d

	measure _mURL = (COUNTA(Org[URL-Main])/countrows(Org))
		formatString: 0%;-0%;0%
		lineageTag: 38c7f6c1-b8e2-487b-aa9f-84eaccdceeb8

	column Organisation
		dataType: string
		lineageTag: af2a3529-8de3-40fa-ad3c-269749e0fef0
		summarizeBy: none
		sourceColumn: Organisation

		annotation SummarizationSetBy = Automatic

	column Mission
		dataType: string
		lineageTag: 6f63f450-3264-43a9-9dcc-62e463a6e74b
		summarizeBy: none
		sourceColumn: Mission

		annotation SummarizationSetBy = Automatic

	column 'Activities AI'
		dataType: string
		lineageTag: 436b501d-5207-43cf-9953-75a5549227cd
		summarizeBy: none
		sourceColumn: Activities AI

		annotation SummarizationSetBy = Automatic

	column Misc
		dataType: string
		lineageTag: 09a5a5ba-722f-4d86-adc8-54d30949eea1
		summarizeBy: none
		sourceColumn: Misc

		annotation SummarizationSetBy = Automatic

	column 'Parent org'
		dataType: string
		lineageTag: bd6b55e7-67a3-41b8-abdb-f74c820ad18e
		summarizeBy: none
		sourceColumn: Parent org

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 552c088e-97e4-4b97-890f-293dbecc4480
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Key Contacts'
		dataType: string
		lineageTag: 0f54e3d0-ad52-4b95-855d-fe38f04b5113
		summarizeBy: none
		sourceColumn: Key Contacts

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 91640236-cc0d-40f0-9e24-e4090118de10
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Organisation-Shortened.1'
		dataType: string
		lineageTag: 0f982550-d827-47e0-9cfb-8c5c0fc85843
		summarizeBy: none
		sourceColumn: Organisation-Shortened.1

		annotation SummarizationSetBy = Automatic

	column 'Organisation-Shortened.2'
		dataType: string
		lineageTag: df576ff7-1067-4f51-851f-fdb8f5d10758
		summarizeBy: none
		sourceColumn: Organisation-Shortened.2

		annotation SummarizationSetBy = Automatic

	column Organisation-Shortened
		dataType: string
		lineageTag: 1bbbf6e0-c2cb-466f-9956-3db1021d49df
		summarizeBy: none
		sourceColumn: Organisation-Shortened

		annotation SummarizationSetBy = Automatic

	column URL-Main
		dataType: string
		lineageTag: 2d2bdd68-9be6-4def-a8c1-7698cb7ca260
		summarizeBy: none
		sourceColumn: URL-Main

		annotation SummarizationSetBy = Automatic

	column URL-Secondary
		dataType: string
		lineageTag: d9bdd3fc-36ca-4e41-89bf-9532e5cd4ca3
		summarizeBy: none
		sourceColumn: URL-Secondary

		annotation SummarizationSetBy = Automatic

	column _%Location = (COUNTA(Org[Location])/countrows(Org))/countrows(Org)
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: 29a62380-9b9d-47a3-af51-f3eb8f8a9a96
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column _%Mission = (COUNTA(Org[Mission])/countrows(Org))/countrows(Org)
		formatString: 0%;-0%;0%
		lineageTag: 40803b1b-92b8-4467-894d-f37e847aa253
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ActiveOrNot
		dataType: string
		lineageTag: fd1b0518-2300-471b-a4ea-d75c1342bc2b
		summarizeBy: none
		sourceColumn: ActiveOrNot

		annotation SummarizationSetBy = Automatic

	column OrgStructure
		dataType: string
		lineageTag: bbf1fc55-7c61-4a42-8cc3-7d5a0c9e5c12
		summarizeBy: none
		sourceColumn: OrgStructure

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: d12c3d20-b57c-407c-bdc8-2a17dfd53811
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column _%Activities = (COUNTA(Org[Activities AI])/countrows(Org))/countrows(Org)
		formatString: 0%;-0%;0%
		lineageTag: 3a7d2c48-247b-4273-927e-faf3ffde2872
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Org = m
		mode: import
		queryGroup: 3-Load
		source =
				let
				    Source = #"010_tblOrg-Formatting",
				    #"Replaced blanks with nulls" = Table.ReplaceValue(Source,"",null,Replacer.ReplaceValue,{"Organisation", "URL-Main", "URL-Secondary", "Mission", "Activities AI", "Status", "Key Contacts", "Parent org", "Location", "Misc", "Organisation-Shortened.1", "Organisation-Shortened.2", "Organisation-Shortened"}),
				    #"Replaced mere linefeeds with nulls" = Table.ReplaceValue(#"Replaced blanks with nulls","#(lf)",null,Replacer.ReplaceValue,{"Organisation", "URL-Main", "URL-Secondary", "Mission", "Activities AI", "Status", "Key Contacts", "Parent org", "Location", "Misc", "Organisation-Shortened.1", "Organisation-Shortened.2", "Organisation-Shortened"})
				in
				    #"Replaced mere linefeeds with nulls"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

